### ISSUE TITLE
Struttura del PDQ

### ISSUE THREAD

**Issue by Jatus93** [TennersUnipd/sweDocs#39]
- [x] #26)Sezione Introduttiva
- [ ] #27)Visione generale della strategia di gestione della qualità:
- [ ] - #28)Obiettivi della qualità
- [ ] - #29)Scadenze temporali che intendiamo seguire
- [ ] #30)Strategia di gestione della qualità nel dettaglio
- [x] #31)Capability Maturity Model (way of working)
- [ ] #34)Come gestiremo la parte di sviluppo dei test
- [ ] #32)Standard ISO/IEC 9126 (qualità del software)
- [ ] #33)PDCA(Plan Do Check Act) Implementazione di ISO 9001

**Comment by simonefranconetti** [comment]
- [ ] Sezione introduttiva (#27, #28, #29, #30)

- [ ] Qualità di prodotto (#32)

- [ ] Qualità di processo (#31, #33)

- [ ] Specifica dei test (#34)
